/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAReceberRouteImport } from './routes/_authenticated/a-receber'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedDreRouteImport } from './routes/_authenticated/dre'
import { Route as AuthenticatedExportacoesRouteImport } from './routes/_authenticated/exportacoes'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedNotasRouteImport } from './routes/_authenticated/notas'
import { Route as AuthenticatedNovaOsRouteImport } from './routes/_authenticated/nova-os'
import { Route as AuthenticatedOrigensRouteImport } from './routes/_authenticated/origens'
import { Route as AuthenticatedOssRouteImport } from './routes/_authenticated/oss'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedRotasRouteImport } from './routes/_authenticated/rotas'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedCrmCampanhasRouteImport } from './routes/_authenticated/crm/campanhas'
import { Route as AuthenticatedCrmFunilRouteImport } from './routes/_authenticated/crm/funil'
import { Route as AuthenticatedCrmImportarRouteImport } from './routes/_authenticated/crm/importar'
import { Route as AuthenticatedCrmIntegracoesRouteImport } from './routes/_authenticated/crm/integracoes'
import { Route as AuthenticatedCrmLeadsRouteImport } from './routes/_authenticated/crm/leads'
import { Route as AuthenticatedCrmRepescagensRouteImport } from './routes/_authenticated/crm/repescagens'
import { Route as AuthenticatedCrmVisaoGeralRouteImport } from './routes/_authenticated/crm/visao-geral'
import { Route as AuthenticatedCrmWhatsappRouteImport } from './routes/_authenticated/crm/whatsapp'
import { Route as AuthenticatedNexaEmpresasRouteImport } from './routes/_authenticated/nexa/empresas'
import { Route as AuthenticatedOrcamentosIndexRouteImport } from './routes/_authenticated/orcamentos/index'
import { Route as AuthenticatedOrcamentosQuoteIdRouteImport } from './routes/_authenticated/orcamentos/$quoteId'
import { Route as AuthenticatedOsOsNumberRouteImport } from './routes/_authenticated/os.$osNumber'
import { Route as AuthenticatedCrmLeadLeadIdRouteImport } from './routes/_authenticated/crm/lead.$leadId'
import { Route as ApiPublicHooksMonthlyMileageClosingRouteImport } from './routes/api/public/hooks/monthly-mileage-closing'
import { Route as ApiPublicHooksRecurringExpensesRouteImport } from './routes/api/public/hooks/recurring-expenses'
import { Route as ApiPublicHooksWhatsappRouteImport } from './routes/api/public/hooks/whatsapp'
import { Route as ApiPublicHooksLeadsSourceTypeTokenRouteImport } from './routes/api/public/hooks/leads.$sourceType.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAReceberRoute = AuthenticatedAReceberRouteImport.update({
  id: '/a-receber',
  path: '/a-receber',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDreRoute = AuthenticatedDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportacoesRoute =
  AuthenticatedExportacoesRouteImport.update({
    id: '/exportacoes',
    path: '/exportacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotasRoute = AuthenticatedNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNovaOsRoute = AuthenticatedNovaOsRouteImport.update({
  id: '/nova-os',
  path: '/nova-os',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrigensRoute = AuthenticatedOrigensRouteImport.update({
  id: '/origens',
  path: '/origens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOssRoute = AuthenticatedOssRouteImport.update({
  id: '/oss',
  path: '/oss',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotasRoute = AuthenticatedRotasRouteImport.update({
  id: '/rotas',
  path: '/rotas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmCampanhasRoute =
  AuthenticatedCrmCampanhasRouteImport.update({
    id: '/crm/campanhas',
    path: '/crm/campanhas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmFunilRoute = AuthenticatedCrmFunilRouteImport.update({
  id: '/crm/funil',
  path: '/crm/funil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmImportarRoute =
  AuthenticatedCrmImportarRouteImport.update({
    id: '/crm/importar',
    path: '/crm/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmIntegracoesRoute =
  AuthenticatedCrmIntegracoesRouteImport.update({
    id: '/crm/integracoes',
    path: '/crm/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmLeadsRoute = AuthenticatedCrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRepescagensRoute =
  AuthenticatedCrmRepescagensRouteImport.update({
    id: '/crm/repescagens',
    path: '/crm/repescagens',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmVisaoGeralRoute =
  AuthenticatedCrmVisaoGeralRouteImport.update({
    id: '/crm/visao-geral',
    path: '/crm/visao-geral',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmWhatsappRoute =
  AuthenticatedCrmWhatsappRouteImport.update({
    id: '/crm/whatsapp',
    path: '/crm/whatsapp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNexaEmpresasRoute =
  AuthenticatedNexaEmpresasRouteImport.update({
    id: '/nexa/empresas',
    path: '/nexa/empresas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentosIndexRoute =
  AuthenticatedOrcamentosIndexRouteImport.update({
    id: '/orcamentos/',
    path: '/orcamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrcamentosQuoteIdRoute =
  AuthenticatedOrcamentosQuoteIdRouteImport.update({
    id: '/orcamentos/$quoteId',
    path: '/orcamentos/$quoteId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOsOsNumberRoute = AuthenticatedOsOsNumberRouteImport.update({
  id: '/os/$osNumber',
  path: '/os/$osNumber',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmLeadLeadIdRoute =
  AuthenticatedCrmLeadLeadIdRouteImport.update({
    id: '/crm/lead/$leadId',
    path: '/crm/lead/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksMonthlyMileageClosingRoute =
  ApiPublicHooksMonthlyMileageClosingRouteImport.update({
    id: '/api/public/hooks/monthly-mileage-closing',
    path: '/api/public/hooks/monthly-mileage-closing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecurringExpensesRoute =
  ApiPublicHooksRecurringExpensesRouteImport.update({
    id: '/api/public/hooks/recurring-expenses',
    path: '/api/public/hooks/recurring-expenses',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWhatsappRoute = ApiPublicHooksWhatsappRouteImport.update({
  id: '/api/public/hooks/whatsapp',
  path: '/api/public/hooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksLeadsSourceTypeTokenRoute =
  ApiPublicHooksLeadsSourceTypeTokenRouteImport.update({
    id: '/api/public/hooks/leads/$sourceType/$token',
    path: '/api/public/hooks/leads/$sourceType/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/a-receber': typeof AuthenticatedAReceberRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/dre': typeof AuthenticatedDreRoute
  '/exportacoes': typeof AuthenticatedExportacoesRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/nova-os': typeof AuthenticatedNovaOsRoute
  '/origens': typeof AuthenticatedOrigensRoute
  '/oss': typeof AuthenticatedOssRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/rotas': typeof AuthenticatedRotasRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/crm/campanhas': typeof AuthenticatedCrmCampanhasRoute
  '/crm/funil': typeof AuthenticatedCrmFunilRoute
  '/crm/importar': typeof AuthenticatedCrmImportarRoute
  '/crm/integracoes': typeof AuthenticatedCrmIntegracoesRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/crm/repescagens': typeof AuthenticatedCrmRepescagensRoute
  '/crm/visao-geral': typeof AuthenticatedCrmVisaoGeralRoute
  '/crm/whatsapp': typeof AuthenticatedCrmWhatsappRoute
  '/nexa/empresas': typeof AuthenticatedNexaEmpresasRoute
  '/orcamentos/$quoteId': typeof AuthenticatedOrcamentosQuoteIdRoute
  '/os/$osNumber': typeof AuthenticatedOsOsNumberRoute
  '/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/crm/lead/$leadId': typeof AuthenticatedCrmLeadLeadIdRoute
  '/api/public/hooks/monthly-mileage-closing': typeof ApiPublicHooksMonthlyMileageClosingRoute
  '/api/public/hooks/recurring-expenses': typeof ApiPublicHooksRecurringExpensesRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/api/public/hooks/leads/$sourceType/$token': typeof ApiPublicHooksLeadsSourceTypeTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/a-receber': typeof AuthenticatedAReceberRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/dre': typeof AuthenticatedDreRoute
  '/exportacoes': typeof AuthenticatedExportacoesRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/notas': typeof AuthenticatedNotasRoute
  '/nova-os': typeof AuthenticatedNovaOsRoute
  '/origens': typeof AuthenticatedOrigensRoute
  '/oss': typeof AuthenticatedOssRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/rotas': typeof AuthenticatedRotasRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/crm/campanhas': typeof AuthenticatedCrmCampanhasRoute
  '/crm/funil': typeof AuthenticatedCrmFunilRoute
  '/crm/importar': typeof AuthenticatedCrmImportarRoute
  '/crm/integracoes': typeof AuthenticatedCrmIntegracoesRoute
  '/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/crm/repescagens': typeof AuthenticatedCrmRepescagensRoute
  '/crm/visao-geral': typeof AuthenticatedCrmVisaoGeralRoute
  '/crm/whatsapp': typeof AuthenticatedCrmWhatsappRoute
  '/nexa/empresas': typeof AuthenticatedNexaEmpresasRoute
  '/orcamentos/$quoteId': typeof AuthenticatedOrcamentosQuoteIdRoute
  '/os/$osNumber': typeof AuthenticatedOsOsNumberRoute
  '/orcamentos': typeof AuthenticatedOrcamentosIndexRoute
  '/crm/lead/$leadId': typeof AuthenticatedCrmLeadLeadIdRoute
  '/api/public/hooks/monthly-mileage-closing': typeof ApiPublicHooksMonthlyMileageClosingRoute
  '/api/public/hooks/recurring-expenses': typeof ApiPublicHooksRecurringExpensesRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/api/public/hooks/leads/$sourceType/$token': typeof ApiPublicHooksLeadsSourceTypeTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/a-receber': typeof AuthenticatedAReceberRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/dre': typeof AuthenticatedDreRoute
  '/_authenticated/exportacoes': typeof AuthenticatedExportacoesRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/notas': typeof AuthenticatedNotasRoute
  '/_authenticated/nova-os': typeof AuthenticatedNovaOsRoute
  '/_authenticated/origens': typeof AuthenticatedOrigensRoute
  '/_authenticated/oss': typeof AuthenticatedOssRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/rotas': typeof AuthenticatedRotasRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/crm/campanhas': typeof AuthenticatedCrmCampanhasRoute
  '/_authenticated/crm/funil': typeof AuthenticatedCrmFunilRoute
  '/_authenticated/crm/importar': typeof AuthenticatedCrmImportarRoute
  '/_authenticated/crm/integracoes': typeof AuthenticatedCrmIntegracoesRoute
  '/_authenticated/crm/leads': typeof AuthenticatedCrmLeadsRoute
  '/_authenticated/crm/repescagens': typeof AuthenticatedCrmRepescagensRoute
  '/_authenticated/crm/visao-geral': typeof AuthenticatedCrmVisaoGeralRoute
  '/_authenticated/crm/whatsapp': typeof AuthenticatedCrmWhatsappRoute
  '/_authenticated/nexa/empresas': typeof AuthenticatedNexaEmpresasRoute
  '/_authenticated/orcamentos/$quoteId': typeof AuthenticatedOrcamentosQuoteIdRoute
  '/_authenticated/os/$osNumber': typeof AuthenticatedOsOsNumberRoute
  '/_authenticated/orcamentos/': typeof AuthenticatedOrcamentosIndexRoute
  '/_authenticated/crm/lead/$leadId': typeof AuthenticatedCrmLeadLeadIdRoute
  '/api/public/hooks/monthly-mileage-closing': typeof ApiPublicHooksMonthlyMileageClosingRoute
  '/api/public/hooks/recurring-expenses': typeof ApiPublicHooksRecurringExpensesRoute
  '/api/public/hooks/whatsapp': typeof ApiPublicHooksWhatsappRoute
  '/api/public/hooks/leads/$sourceType/$token': typeof ApiPublicHooksLeadsSourceTypeTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/a-receber'
    | '/agenda'
    | '/configuracoes'
    | '/despesas'
    | '/dre'
    | '/exportacoes'
    | '/inicio'
    | '/mensagens'
    | '/notas'
    | '/nova-os'
    | '/origens'
    | '/oss'
    | '/pagamentos'
    | '/rotas'
    | '/servicos'
    | '/usuarios'
    | '/crm/campanhas'
    | '/crm/funil'
    | '/crm/importar'
    | '/crm/integracoes'
    | '/crm/leads'
    | '/crm/repescagens'
    | '/crm/visao-geral'
    | '/crm/whatsapp'
    | '/nexa/empresas'
    | '/orcamentos/$quoteId'
    | '/os/$osNumber'
    | '/orcamentos/'
    | '/crm/lead/$leadId'
    | '/api/public/hooks/monthly-mileage-closing'
    | '/api/public/hooks/recurring-expenses'
    | '/api/public/hooks/whatsapp'
    | '/api/public/hooks/leads/$sourceType/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/a-receber'
    | '/agenda'
    | '/configuracoes'
    | '/despesas'
    | '/dre'
    | '/exportacoes'
    | '/inicio'
    | '/mensagens'
    | '/notas'
    | '/nova-os'
    | '/origens'
    | '/oss'
    | '/pagamentos'
    | '/rotas'
    | '/servicos'
    | '/usuarios'
    | '/crm/campanhas'
    | '/crm/funil'
    | '/crm/importar'
    | '/crm/integracoes'
    | '/crm/leads'
    | '/crm/repescagens'
    | '/crm/visao-geral'
    | '/crm/whatsapp'
    | '/nexa/empresas'
    | '/orcamentos/$quoteId'
    | '/os/$osNumber'
    | '/orcamentos'
    | '/crm/lead/$leadId'
    | '/api/public/hooks/monthly-mileage-closing'
    | '/api/public/hooks/recurring-expenses'
    | '/api/public/hooks/whatsapp'
    | '/api/public/hooks/leads/$sourceType/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/a-receber'
    | '/_authenticated/agenda'
    | '/_authenticated/configuracoes'
    | '/_authenticated/despesas'
    | '/_authenticated/dre'
    | '/_authenticated/exportacoes'
    | '/_authenticated/inicio'
    | '/_authenticated/mensagens'
    | '/_authenticated/notas'
    | '/_authenticated/nova-os'
    | '/_authenticated/origens'
    | '/_authenticated/oss'
    | '/_authenticated/pagamentos'
    | '/_authenticated/rotas'
    | '/_authenticated/servicos'
    | '/_authenticated/usuarios'
    | '/_authenticated/crm/campanhas'
    | '/_authenticated/crm/funil'
    | '/_authenticated/crm/importar'
    | '/_authenticated/crm/integracoes'
    | '/_authenticated/crm/leads'
    | '/_authenticated/crm/repescagens'
    | '/_authenticated/crm/visao-geral'
    | '/_authenticated/crm/whatsapp'
    | '/_authenticated/nexa/empresas'
    | '/_authenticated/orcamentos/$quoteId'
    | '/_authenticated/os/$osNumber'
    | '/_authenticated/orcamentos/'
    | '/_authenticated/crm/lead/$leadId'
    | '/api/public/hooks/monthly-mileage-closing'
    | '/api/public/hooks/recurring-expenses'
    | '/api/public/hooks/whatsapp'
    | '/api/public/hooks/leads/$sourceType/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksMonthlyMileageClosingRoute: typeof ApiPublicHooksMonthlyMileageClosingRoute
  ApiPublicHooksRecurringExpensesRoute: typeof ApiPublicHooksRecurringExpensesRoute
  ApiPublicHooksWhatsappRoute: typeof ApiPublicHooksWhatsappRoute
  ApiPublicHooksLeadsSourceTypeTokenRoute: typeof ApiPublicHooksLeadsSourceTypeTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/a-receber': {
      id: '/_authenticated/a-receber'
      path: '/a-receber'
      fullPath: '/a-receber'
      preLoaderRoute: typeof AuthenticatedAReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dre': {
      id: '/_authenticated/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof AuthenticatedDreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exportacoes': {
      id: '/_authenticated/exportacoes'
      path: '/exportacoes'
      fullPath: '/exportacoes'
      preLoaderRoute: typeof AuthenticatedExportacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notas': {
      id: '/_authenticated/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof AuthenticatedNotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-os': {
      id: '/_authenticated/nova-os'
      path: '/nova-os'
      fullPath: '/nova-os'
      preLoaderRoute: typeof AuthenticatedNovaOsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/origens': {
      id: '/_authenticated/origens'
      path: '/origens'
      fullPath: '/origens'
      preLoaderRoute: typeof AuthenticatedOrigensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/oss': {
      id: '/_authenticated/oss'
      path: '/oss'
      fullPath: '/oss'
      preLoaderRoute: typeof AuthenticatedOssRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotas': {
      id: '/_authenticated/rotas'
      path: '/rotas'
      fullPath: '/rotas'
      preLoaderRoute: typeof AuthenticatedRotasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/campanhas': {
      id: '/_authenticated/crm/campanhas'
      path: '/crm/campanhas'
      fullPath: '/crm/campanhas'
      preLoaderRoute: typeof AuthenticatedCrmCampanhasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/funil': {
      id: '/_authenticated/crm/funil'
      path: '/crm/funil'
      fullPath: '/crm/funil'
      preLoaderRoute: typeof AuthenticatedCrmFunilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/importar': {
      id: '/_authenticated/crm/importar'
      path: '/crm/importar'
      fullPath: '/crm/importar'
      preLoaderRoute: typeof AuthenticatedCrmImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/integracoes': {
      id: '/_authenticated/crm/integracoes'
      path: '/crm/integracoes'
      fullPath: '/crm/integracoes'
      preLoaderRoute: typeof AuthenticatedCrmIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/leads': {
      id: '/_authenticated/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AuthenticatedCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/repescagens': {
      id: '/_authenticated/crm/repescagens'
      path: '/crm/repescagens'
      fullPath: '/crm/repescagens'
      preLoaderRoute: typeof AuthenticatedCrmRepescagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/visao-geral': {
      id: '/_authenticated/crm/visao-geral'
      path: '/crm/visao-geral'
      fullPath: '/crm/visao-geral'
      preLoaderRoute: typeof AuthenticatedCrmVisaoGeralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/whatsapp': {
      id: '/_authenticated/crm/whatsapp'
      path: '/crm/whatsapp'
      fullPath: '/crm/whatsapp'
      preLoaderRoute: typeof AuthenticatedCrmWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nexa/empresas': {
      id: '/_authenticated/nexa/empresas'
      path: '/nexa/empresas'
      fullPath: '/nexa/empresas'
      preLoaderRoute: typeof AuthenticatedNexaEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/': {
      id: '/_authenticated/orcamentos/'
      path: '/orcamentos'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof AuthenticatedOrcamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamentos/$quoteId': {
      id: '/_authenticated/orcamentos/$quoteId'
      path: '/orcamentos/$quoteId'
      fullPath: '/orcamentos/$quoteId'
      preLoaderRoute: typeof AuthenticatedOrcamentosQuoteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/$osNumber': {
      id: '/_authenticated/os/$osNumber'
      path: '/os/$osNumber'
      fullPath: '/os/$osNumber'
      preLoaderRoute: typeof AuthenticatedOsOsNumberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/lead/$leadId': {
      id: '/_authenticated/crm/lead/$leadId'
      path: '/crm/lead/$leadId'
      fullPath: '/crm/lead/$leadId'
      preLoaderRoute: typeof AuthenticatedCrmLeadLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/monthly-mileage-closing': {
      id: '/api/public/hooks/monthly-mileage-closing'
      path: '/api/public/hooks/monthly-mileage-closing'
      fullPath: '/api/public/hooks/monthly-mileage-closing'
      preLoaderRoute: typeof ApiPublicHooksMonthlyMileageClosingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recurring-expenses': {
      id: '/api/public/hooks/recurring-expenses'
      path: '/api/public/hooks/recurring-expenses'
      fullPath: '/api/public/hooks/recurring-expenses'
      preLoaderRoute: typeof ApiPublicHooksRecurringExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp': {
      id: '/api/public/hooks/whatsapp'
      path: '/api/public/hooks/whatsapp'
      fullPath: '/api/public/hooks/whatsapp'
      preLoaderRoute: typeof ApiPublicHooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/leads/$sourceType/$token': {
      id: '/api/public/hooks/leads/$sourceType/$token'
      path: '/api/public/hooks/leads/$sourceType/$token'
      fullPath: '/api/public/hooks/leads/$sourceType/$token'
      preLoaderRoute: typeof ApiPublicHooksLeadsSourceTypeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAReceberRoute: typeof AuthenticatedAReceberRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedDreRoute: typeof AuthenticatedDreRoute
  AuthenticatedExportacoesRoute: typeof AuthenticatedExportacoesRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedNotasRoute: typeof AuthenticatedNotasRoute
  AuthenticatedNovaOsRoute: typeof AuthenticatedNovaOsRoute
  AuthenticatedOrigensRoute: typeof AuthenticatedOrigensRoute
  AuthenticatedOssRoute: typeof AuthenticatedOssRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedRotasRoute: typeof AuthenticatedRotasRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedCrmCampanhasRoute: typeof AuthenticatedCrmCampanhasRoute
  AuthenticatedCrmFunilRoute: typeof AuthenticatedCrmFunilRoute
  AuthenticatedCrmImportarRoute: typeof AuthenticatedCrmImportarRoute
  AuthenticatedCrmIntegracoesRoute: typeof AuthenticatedCrmIntegracoesRoute
  AuthenticatedCrmLeadsRoute: typeof AuthenticatedCrmLeadsRoute
  AuthenticatedCrmRepescagensRoute: typeof AuthenticatedCrmRepescagensRoute
  AuthenticatedCrmVisaoGeralRoute: typeof AuthenticatedCrmVisaoGeralRoute
  AuthenticatedCrmWhatsappRoute: typeof AuthenticatedCrmWhatsappRoute
  AuthenticatedNexaEmpresasRoute: typeof AuthenticatedNexaEmpresasRoute
  AuthenticatedOrcamentosQuoteIdRoute: typeof AuthenticatedOrcamentosQuoteIdRoute
  AuthenticatedOsOsNumberRoute: typeof AuthenticatedOsOsNumberRoute
  AuthenticatedOrcamentosIndexRoute: typeof AuthenticatedOrcamentosIndexRoute
  AuthenticatedCrmLeadLeadIdRoute: typeof AuthenticatedCrmLeadLeadIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAReceberRoute: AuthenticatedAReceberRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedDreRoute: AuthenticatedDreRoute,
  AuthenticatedExportacoesRoute: AuthenticatedExportacoesRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedNotasRoute: AuthenticatedNotasRoute,
  AuthenticatedNovaOsRoute: AuthenticatedNovaOsRoute,
  AuthenticatedOrigensRoute: AuthenticatedOrigensRoute,
  AuthenticatedOssRoute: AuthenticatedOssRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedRotasRoute: AuthenticatedRotasRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedCrmCampanhasRoute: AuthenticatedCrmCampanhasRoute,
  AuthenticatedCrmFunilRoute: AuthenticatedCrmFunilRoute,
  AuthenticatedCrmImportarRoute: AuthenticatedCrmImportarRoute,
  AuthenticatedCrmIntegracoesRoute: AuthenticatedCrmIntegracoesRoute,
  AuthenticatedCrmLeadsRoute: AuthenticatedCrmLeadsRoute,
  AuthenticatedCrmRepescagensRoute: AuthenticatedCrmRepescagensRoute,
  AuthenticatedCrmVisaoGeralRoute: AuthenticatedCrmVisaoGeralRoute,
  AuthenticatedCrmWhatsappRoute: AuthenticatedCrmWhatsappRoute,
  AuthenticatedNexaEmpresasRoute: AuthenticatedNexaEmpresasRoute,
  AuthenticatedOrcamentosQuoteIdRoute: AuthenticatedOrcamentosQuoteIdRoute,
  AuthenticatedOsOsNumberRoute: AuthenticatedOsOsNumberRoute,
  AuthenticatedOrcamentosIndexRoute: AuthenticatedOrcamentosIndexRoute,
  AuthenticatedCrmLeadLeadIdRoute: AuthenticatedCrmLeadLeadIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksMonthlyMileageClosingRoute:
    ApiPublicHooksMonthlyMileageClosingRoute,
  ApiPublicHooksRecurringExpensesRoute: ApiPublicHooksRecurringExpensesRoute,
  ApiPublicHooksWhatsappRoute: ApiPublicHooksWhatsappRoute,
  ApiPublicHooksLeadsSourceTypeTokenRoute:
    ApiPublicHooksLeadsSourceTypeTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
