// Originally generated by Lovable; now maintained here (also sends the active company).
import { createMiddleware } from "@tanstack/react-start";
import { supabase } from "./client";
import { EMPRESA_HEADER, getEmpresaAtiva } from "@/lib/empresa-ativa";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    const empresa = getEmpresaAtiva();
    return next({
      headers: {
        ...(token ? { Authorization: `Bearer ${token}` } : {}),
        ...(empresa ? { [EMPRESA_HEADER]: empresa } : {}),
      },
    });
  },
);
